server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          # 주의점 아래 keycloak 이름은 provider 에서도 똑같이 있어야함, 한세트로 이름이 같아야한다. 아니면 에러발생
          # keycloak 이 registration 에 정의 되어있따다면 provider 에서도 keycloak 이 정의 되어 있어야한다
          keycloak:
            client-id: oauth2-client-app
            client-secret: UAVYZDOh5rdpQxuK4EQ9sQaZh3K9mlVi
            client-name: oauth2-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: openid,email,profile
          # keycloak2 가 registration 에 정의 되어있다면 provider 에서도 keycloak2가 정의 되어 있어야한다
          keycloak2:
            client-id: oauth3-client-app
            client-secret: NIjFfDn85bLivzKYV1ABGsPcLvdRgzlI
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak2
#            아래의 값은 없으면 기본값으로 설정된다.
#            client-name: oauth3-client-app
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
#            scope: openid,email,profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/oauth2
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            user-name-attribute: preferred_username
          keycloak2:
            issuer-uri: http://localhost:8080/realms/oauth3
            user-name-attribute: preferred_username
#            아래의 값은 없으면 issuer-uri 에서 가져온 값으로 설정된다.
#            authorization-uri: http://localhost:8080/realms/oauth3/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/realms/oauth3/protocol/openid-connect/token
#            user-info-uri: http://localhost:8080/realms/oauth3/protocol/openid-connect/userinfo
#            jwk-set-uri: http://localhost:8080/realms/oauth3/protocol/openid-connect/certs